### ISSUE TITLE
margin between banner section and welcome section

### ISSUE THREAD

**Issue by Alexg1021** [geekwise-alonzo-yrigollen/dustybuns#1]
adding margin on top and bottom will give the project a nicer aesthetic feel

**Comment by Alexg1021** [comment]
![screen shot 2016-03-21 at 1 34 18 pm](https://cloud.githubusercontent.com/assets/11038686/13933318/d19414cc-ef69-11e5-952c-8777f11fc0c9.png)

**Comment by geekwise-alonzo-yrigollen** [comment]
complete, margin added as specified

**Comment by geekwise-alonzo-yrigollen** [comment]
good morning alex, i put margin in...when you get time can you close this issue
