### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by haniali1234** [geekwise-alonzo-yrigollen/dustybuns#2]
Page: home
Issue: navbar
photo:
![screen shot 2016-03-21 at 2 46 41 pm](https://cloud.githubusercontent.com/assets/11038599/13935305/f3676d42-ef73-11e5-87ef-0e99a322de8f.png)

**Comment by geekwise-alonzo-yrigollen** [comment]
home page nav resolved. Have a great evening... L8
