### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by haniali1234** [geekwise-alonzo-yrigollen/dustybuns#3]
page: home
issue: font awesome
photo: 
![screen shot 2016-03-22 at 1 11 38 pm](https://cloud.githubusercontent.com/assets/11038599/13966485/d9220c78-f02f-11e5-8dab-947896b54be9.png)

**Comment by geekwise-alonzo-yrigollen** [comment]
sup ther Hani Ali! hope you enjoying your day. resolved...
