### ISSUE TITLE
social media links alignment

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-alonzo-yrigollen/dustybuns#6]
issue: social media links alignment
pages: global

how yours looks:
![screen shot 2016-03-23 at 10 08 52 am](https://cloud.githubusercontent.com/assets/7436666/13993847/4c03e54a-f0df-11e5-8620-bcd18003794a.png)

how it should look:
![screen shot 2016-03-23 at 10 08 17 am](https://cloud.githubusercontent.com/assets/7436666/13993825/37a8f324-f0df-11e5-8990-4e7160b51101.png)

options:
text-align center for all 3 columns

**Comment by geekwise-alonzo-yrigollen** [comment]
Good morning Sam; 

I aligned the media icons; when you get time can you close this issue out, I'm gonna jump to the  favicon issue now? Make it a great day Sam
