### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by haniali1234** [geekwise-alonzo-yrigollen/dustybuns#8]
page:  Home
issue. Font of the logo.  Same thing applies to all the page. 
photo: 
![screen shot 2016-04-04 at 8 21 13 am](https://cloud.githubusercontent.com/assets/11038599/14252951/644d4c28-fa3e-11e5-80c3-5289383dd530.png)

**Comment by geekwise-alonzo-yrigollen** [comment]
completed buddy.

**Comment by haniali1234** [comment]
Only Dusty buns has font family. 
the other one "Fresh local seasonal" doesnt have font family on it

**Comment by geekwise-alonzo-yrigollen** [comment]
got it...we good?

**Comment by haniali1234** [comment]
now  Dusty buns doesnt have font.

**Comment by geekwise-alonzo-yrigollen** [comment]
I did the same thing; github issue...i could had sworn i pushed to gh-pages before saying "got-it". 

Gonna do issue #9 Welcome to dusty buns <em>font<em>

**Comment by geekwise-alonzo-yrigollen** [comment]
issue #9 welcome to dusty buns pushed
